<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AppointmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AppointmentRepository extends EntityRepository
{
	public function getAppointmentsOfDay($date = null)
    {
      (is_null($date)) ? $date = new \Datetime('now') : $date = new \Datetime($date);
      $date = $date->format('Y-m-d').' 00:00:00';

      $query = $this->getEntityManager()->createQuery("
      	SELECT  a, s, c, sv, stf, r
				FROM AppBundle:Appointment a
				JOIN a.schedules s
				JOIN a.customer c
				JOIN s.service sv
				JOIN s.staff stf
				JOIN s.room r
				WHERE s.scheduleDate = :date
      	")
      ->setParameter('date', $date);

      return $query->getArrayResult();
    }
}
