<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CustomerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CustomerRepository extends EntityRepository
{
	public function findByTerm($term)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT customer.id as id,
                   customer.name as label,
                   customer.lastName as lastName,
                   customer.address as adress
            FROM AppBundle:Customer customer
            WHERE customer.name LIKE :term
            OR customer.lastName LIKE :term
        ")->setParameter('term', '%' . $term . '%');

        return $query->getArrayResult();
    }

    public function findCustomer($customer_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT customer
            FROM AppBundle:Customer customer
            WHERE customer.id = :customer_id
        ")->setParameter('customer_id', $customer_id);

        return $query->getSingleResult();
    }
}
