<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ServiceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ServiceRepository extends EntityRepository
{
	public function findAllServices()
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT service
            FROM AppBundle:Service service
            ORDER BY service.name ASC"
        );

        return $query->getArrayResult();
    }

    public function findService($service_id)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT service
            FROM AppBundle:Service service
            WHERE service.id = :service_id
        ")->setParameter('service_id', $service_id);

        return $query->getArrayResult();
    }

    public function findByTerm($term)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT service.id as id,
                   service.name as label,
                   service.price as price
            FROM AppBundle:Service service
            WHERE service.name LIKE :term
        ")->setParameter('term', '%' . $term . '%');

        return $query->getArrayResult();
    }
}
