<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * StaffRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StaffRepository extends EntityRepository
{
	public function findByTerm($term)
    {
        $query = $this->getEntityManager()->createQuery("
            SELECT staff.id as id,
                   staff.name as label,
                   staff.lastName as lastName
            FROM AppBundle:Staff staff
            WHERE staff.name LIKE :term
            OR staff.lastName LIKE :term
        ")->setParameter('term', '%' . $term . '%');

        return $query->getArrayResult();
    }
}
